---
# tasks file for nginx_proxy

- name: setup nginx
  apt:
    name: nginx
    state: present
  become: true

- name: set proxy
  template:
    src: proxy_nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Перезапуск Nginx
