---
# tasks file for default_packages
- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname" 
- name: pkg
  apt: 
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ packages_to_install }}"
  when: ansible_distribution == "Ubuntu"
