all:
  children:
    linux:
      children:
        allvm:
          hosts:
            vm1:
              ansible_host: 84.201.159.222
            vm2:
              ansible_host: 51.250.67.113
        nginx:
          hosts:
            vm1:
            vm2:
        proxy:
          hosts:
            vm1:
        web:
          hosts:
            vm2:
  vars:
    ansible_user: "test"
    ansible_ssh_private_key_file: "~/ed22"
    ansible_connection: ssh
    ansible_become: true

