---
- name: default package
  hosts: all
  become: true  
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: nginx custom 
  hosts: web  
  become: true  
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: nginx proxy 
  hosts: proxy  
  become: true  
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

