---
# tasks file for nginx_custom

- name: install nginx 
  apt:
    name: "nginx"
    state: present

- name: swap site 
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
  when: "'vm2' in inventory_hostname" 
  notify: "nginx reload"
